name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t dattasandeep/genesis-backend1:latest .
          docker push dattasandeep/genesis-backend1:latest
          
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull dattasandeep/genesis-backend1:latest
      - name: Stop old container
        run: docker stop genesis-server
      - name: Delete old container
        run: docker rm -f genesis-server
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name genesis-server dattasandeep/genesis-backend1:latest
